;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-colon
        c-electric-delete-forward
        c-electric-semi&comma
        electric-pair-mode
        haskell-indentation-common-electric-command
        toggle-frame-fullscreen
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-lt-gt
        replace-string
        yas-expand
        ))
